version: '2'
networks:
  front:
    driver: bridge
  back:
    driver: bridge
services:
  app:
    build:
      context: ./our_app/
    volumes:
      - ../webroot:/var/www/our_app:Z
    networks:
      - front
      - back
  nginx:
    build:
      context: ./nginx/
    networks:
      front:
        aliases:
          - "our_app.dev"
    ports:
      - "8888:80"
    volumes_from:
      - app
    links:
      - app
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8886:3306"
    volumes:
      - ../db_dump:/docker-entrypoint-initdb.d:Z
    networks:
      - back
